### ISSUE TITLE
good start, but not full height

### ISSUE THREAD

**Issue by laurentdebricon** [tommythorn/Paperlike-Raspberry-Pi-4#1]
![20191104_155949](https://user-images.githubusercontent.com/736104/68130922-80685880-ff1c-11e9-9fe2-f0027ce253f4.jpg)

Hello, thank you and thank you Google, it is working better, 
but the resolution is not full height ...
If you find new tweaks, know that i am here watching this repo :p

Touchscreen is 20px wrong also.

best regards,
Laurent

**Comment by tommythorn** [comment]
Is this still a problem after the most recent changes?

**Comment by gilescope** [comment]
Any ideas why the pi can't drive the full resolution of the panel? - the readme just said that 1600x1200 was the max.

**Comment by tommythorn** [comment]
I didn't write that and it's clear in the settings I gave that the resolution is 2200x1650 so I don't know why he added that.  Next I try, I'll verify and edit that.

However, I will say that in practice, I find the panel pretty much hopeless with that resolution - it just isn't sharp enough to be useful.  I personally use the quarter resolution, 1100x825, which is sadly less useful, but at least readable.

**Comment by tommythorn** [comment]
Wait, do you have a Pro or an HD?  I know knowing of the Pro and anything related to that come from someone else.

**Comment by RaynChen** [comment]
![IMG_1396](https://user-images.githubusercontent.com/8964553/92876506-c34c6400-f43c-11ea-8f95-2c09fbbf5957.JPG)
![IMG_1394](https://user-images.githubusercontent.com/8964553/92875716-e32f5800-f43b-11ea-8fb5-c4b92a881a15.JPG)
![IMG_1399](https://user-images.githubusercontent.com/8964553/92875730-e4f91b80-f43b-11ea-87a3-fa019d804771.JPG)
My PaperLike HD(2018) is working after several attempts, but Chromium address bar is extremely small compared with Document browser....any solution for this?

**Comment by laurentdebricon** [comment]
@RaynChen what have you done to make it work so great like that ? Which settings ? Thanks

**Comment by RaynChen** [comment]
@laurentdebricon just put the edid.dat file to the /boot and modify the config.txt file as Tommy instructed, other display setting just select everything to the largest on system original display setting.  it take me several attempts, but  I guess only thing need to do is "Du courage et continue" , don't forget to reboot.

**Comment by tommythorn** [comment]
Laurent, ça marche ?  Pouvons-nous ferme celui-ci ?
