### ISSUE TITLE
hdmi_enable_4kp60=1 needed on Arch Linux Arm

### ISSUE THREAD

**Issue by ypsu** [tommythorn/Paperlike-Raspberry-Pi-4#4]
Without that option in config.txt I didn't get the full resolution in the framebuffer.
Perhaps might worth a mention in the readme.

Thanks for the awesome instructions, much appreciated!

**Comment by tommythorn** [comment]
Sure. Are you using a Pro or an HD? The latter I assume but want to be sure.

**Comment by ypsu** [comment]
Yeah, the HD one.

**Comment by tommythorn** [comment]
RFR https://github.com/tommythorn/Paperlike-Raspberry-Pi-4/pull/5

**Comment by ypsu** [comment]
Awesome, thank you!
